name: 'Github Organization Activity Report'
description: 'Create a user activity report for a Github organization'
author: 'Daniel Benesch'
inputs:
  token:
    description: 'Github access token for the organization'
    required: true
  organization:
    description: 'The organization to create the report for'
    required: true
  since-days:
    description: 'The number of days in the past to search for activity for'
    required: true
    default: 90
  since:
    description: 'The ISO-8601 since date. "2023-12" is equal to "2023-12-01T00:00:00.000Z"'
  until:
    description: 'The ISO-8601 until date. This value is exclusive. E.g. "2024-01" will include results until "2023-12-31T23:59:59.999Z"'
  analyze-commits:
    description: 'Enable to analyze commits'
    default: true
  analyze-commits-on-all-branches:
    description: 'Enable to analyze commits on all branches. By default only commits on the default branches are analyzed. Ignored if analyze-commits is false'
    default: false
  analyze-issues:
    description: 'Enable to analyze issues'
    default: true
  analyze-issue-comments:
    description: 'Enable to analyze issue comments'
    default: true
  analyze-pull-requests:
    description: 'Enable to analyze pull requests'
    default: true
  analyze-pull-request-comments:
    description: 'Enable to analyze pull requests comments'
    default: true
  analyze-discussions:
    description: 'Enable to analyze discussions'
    default: true
  analyze-discussion-comments:
    description: 'Enable to analyze discussions comments'
    default: true
  create-json:
    description: 'Save the report as json file to this path'
    required: false
    default: false
  create-csv:
    description: 'Save the report as csv file to this path'
    required: false
    default: false
  create-summary:
    description: 'Write the report as step summary to the github action'
    default: true
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'activity'
  color: 'gray-dark'