name: 'Github Organization Activity Report'
description: 'Create a user activity report for a Github organization'
author: 'Daniel Benesch'
inputs:
  token:
    description: 'Github access token for the organization'
    required: true
  organization:
    description: 'The organization to create the report for'
    required: true
  since-days:
    description: 'The number of days in the past to search for activity for'
    required: true
    default: 90
runs:
  using: 'node16'
  main: 'dist/index.js'
